services:
  db:
    image: postgres:14
    container_name: bohdanfsd-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME:-default_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password

    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '1G'

    secrets:
      - db_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bohdanfsd-app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers
    networks:
      - backend

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:


secrets:
  db_password:
    file: ./secrets/db_password.txt
